name: schedule

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  init:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - run: wget https://downloads.wordpress.org/plugin/komito-analytics.1.2.1.zip
      - run: wget https://downloads.wordpress.org/plugin/komito-analytics.zip
